### ISSUE TITLE
Ayanamsa value changes after calling swe_houses_ex

### ISSUE THREAD

**Issue by jamithiran** [ygrenier/SwissEphNet#30] opened 2017-10-22 14:29 UTC
Hello Mr. Grenier,

I have a situation where swe_get_ayanamsa_ut returns a different value after a call to swe_houses_ex. 

The same is not the case when swe_houses is called. Kindly check test code below. 
Appreciate your support.

Cheers
-------------

using System;
using SwissEphNet;

namespace ChkSwissEph
{
    class Program
    {
        static void Main(string[] args)
        {
            //using (var sweph = new SwissEph())
            //{
            //    sweph.swe_set_ephe_path(@"C:\sweph");
            //}

            using (var sweph = new SwissEph())
            {
                double[] planetdata = new double[6];
                double[] dret = new double[2];
                int outdt = 0;
                int outmo = 0;
                int outdy = 0;
                int outhh = 0;
                int outmm = 0;
                double outss = 0;
                string serr = null;

                sweph.swe_utc_time_zone(2000, 10, 22, 17, 30, 25, 5.5, ref outdt, ref outmo, ref outdy, ref outhh, ref outmm, ref outss);
                sweph.swe_utc_to_jd(outdt, outmo, outdy, outhh, outmm, outss, SwissEph.SE_GREG_CAL, dret, ref serr);

                int ipl = 0;
                int iflag = SwissEph.SEFLG_TRUEPOS | SwissEph.SEFLG_SWIEPH | SwissEph.SEFLG_SPEED | SwissEph.SEFLG_TOPOCTR | SwissEph.SEFLG_SIDEREAL;
                double geolon = 78.70972; 
                double geolat = 10.76536; 
                double height = 89;

                sweph.swe_set_topo(geolon, geolat, height);
                sweph.swe_set_sid_mode(5, 0, 0);

                Console.WriteLine(sweph.swe_get_ayanamsa_ut(dret[1]));

                sweph.swe_calc_ut(dret[1], ipl, iflag, planetdata, ref serr);

                double[] cusps = new double[13];
                double[] ascmc = new double[10];

                Console.WriteLine(sweph.swe_get_ayanamsa_ut(dret[1]));

                //Below is not fine
                sweph.swe_houses_ex(dret[1], SwissEph.SEFLG_SIDEREAL, geolat, geolon, 'P', cusps, ascmc);

                //Below is fine
                //sweph.swe_houses(dret[1], geolat, geolon, 'P', cusps, ascmc);
                
                Console.WriteLine(sweph.swe_get_ayanamsa_ut(dret[1]));

                //Console.WriteLine();
                //int x;
                //for (x = 1; x <= 12; x++)
                //{
                //    Console.WriteLine(cusps[x]);
                //}

                Console.Read();
            }
        }
    }
}

**Comment by ygrenier** [comment] 2017-10-22 21:15
Hi, 

Thanks for reporting this issue with code.

I'll try too look it this week (probably next WE because I'm very busy).

Regards,

Yanos

**Comment by ygrenier** [comment] 2017-10-28 05:43
I open the PR #31 but I can't reproduce the issue.

Could you read [my comment](https://github.com/ygrenier/SwissEphNet/pull/31#issuecomment-340141088).

Thanks.

**Comment by jamithiran** [comment] 2017-10-28 06:27
I checked your comment and responded as well. New version gets the correct result. Thank you.

**Comment by ygrenier** [comment] 2017-10-28 06:36
OK good news. I'll close the issue and PR.

**Closed by ygrenier** 2017-10-28 06:36 UTC
